### ISSUE TITLE
Template  has Additional DIV wrapped, why?

### ISSUE THREAD

**Issue by itimryan** [codepb/jquery-template#100]
Each inserted  populated template is wrapped by two layers of div

for example, I have template like this:

<script type="text/html" id="items">
    <a data-href="id" data-format="myUrl" data-format-target="href">
        <h4 data-content="title"></h4>
        <p class="ping" data-content="content"></p>
    </a>
</script>

after I inserted it into the DOM, they look like as below,

<div>
  <div>
    <a data-href="id" data-format="myUrl" data-format-target="href">
        <h4 data-content="title"></h4>
        <p class="ping" data-content="content"></p>
     </a>
 </div>
</div>

Who can tell me the reason?

**Comment by codepb** [comment]
duplicate of #101
