### ISSUE TITLE
NPM install broken

### ISSUE THREAD

**Issue by dabder** [codepb/jquery-template#108]
NPM installation goes wrong because of the latest version available in NPM registry is 1.5.0.

1.5.10 contains a fix in package.json (main attribute). Would you push the 1.5.10 version within NPM central repository ?

Thanks

**Comment by codepb** [comment]
I'll look into getting this fixed

**Comment by codepb** [comment]
version 1.5.10 published

**Comment by dabder** [comment]
Fixed! Thanks
