### ISSUE TITLE
Insert index property on array processing

### ISSUE THREAD

**Issue by sashberd** [codepb/jquery-template#111]
Is there a way to get index of inserted item when we work with array? As I saw in the code you just run over array with for each without index referencing. 
The index property could be useful e.g. in add distinct dynamic id (div0, div1, div2...)

**Comment by codepb** [comment]
I'm not sure how this will work, without making major changes to the plugin (I'd have to add a property you could bind to, only if it was an array. Confusing). Simplest way to do this, add the index to each item yourself before you call the templating plugin.
