### ISSUE TITLE
Use another HTML tag instead of script - new property "templateTag"

### ISSUE THREAD

**Issue by Jacqbus** [codepb/jquery-template#114]
In one of my projects i cannot use "script" HTML tag to contain templates, so i think it'll be good idea to add new property eg. "templateTag" where you can define which HTML tag you use to keep templates.
Of course i bypassed this small issue without problems, but it'll be great feature for all i think.

**Comment by codepb** [comment]
If you wish to create a pull request to support this, I am happy to add it in. You can also use external templates as an alternative.
