### ISSUE TITLE
Create version 2

### ISSUE THREAD

**Issue by codepb** [codepb/jquery-template#46]
I have a number of ideas for version 2 of the plugin. I feel there are a number of things that need to be improved. In order to do this, version 2 would not be backward compatible with version 1. Some things that need addressing:
- change data-content and binding to the innerHTML using the word content. This prevents biding to the attribute "content" currently
- change the data-something tags to be data-template-something tags, keeping everything under the data-template structure, thus avoiding potential conflicts
- simplify the notation somehow. Currently data-template-bind can get rather long and complicated. Is there a better way to do this?
- look at the possibility of introducing a watch on the data and updating the DOM
- potentially include conditional formatting, to render template only if a condition is met

Any other ideas welcome for version 2 of the plugin, or advice around whether this is a good idea.

**Comment by jor77** [comment]
I would suggest adding the possibility to bind to more than a key.
I actually just figured out how to do this with a template formatter but I find it a bit unelegant.

"look at the possibility of introducing a watch on the data and updating the DOM"... maybe also some way to define a function to call so that changing data client side not only update the DOM but also the remote source of data?

**Comment by maciejsaw** [comment]
Did you see way.js? https://github.com/gwendall/way.js?files=1 
This is similar to your approach but has the two-way binding, maybe it's worth to combine efforts?
Way.js misses your flexibility, for example there's no way to control classes via a template.

Also you can take a look at Meteor autorun library, that can easily power that can power the data binding and observation. The challenge might be the "rerender" overhead - we should rerender only the specific DOM part when needed, not the whole list.

**Comment by codepb** [comment]
Thanks, I will check this out. I plan to start work on version 2 sometime soon and I am open to all ideas regarding the way forward and am more than happy to work with other contributors and libraries so please do let me know about things like this.
