### ISSUE TITLE
support class attribute

### ISSUE THREAD

**Issue by emanuelerighetto** [codepb/jquery-template#51]
I've managed to extend the binding with data-class option.
This should add one or more specific css classes to the template.
Just added the following to the bindData function before last statement:

processElements("data-class", template, data, settings, function ($elem, value) {
            $elem.addClass(value);
        });

maybe you could add this to your next release :)

**Comment by erikvanzijst** [comment]
Can this issue be closed? AFAIK data-class works now (I was on 1.4.4 where it didn't, but after upgrading to 1.5.10, it now works).

**Comment by codepb** [comment]
Thanks, closing
