### ISSUE TITLE
Add data-checked attribute

### ISSUE THREAD

**Issue by apbarratt** [codepb/jquery-template#58]
Hi guys,
I don't want to commit this myself because I know it's messy and needs cleaned up but could someone add this function?  The way I'm using it (and the way I imagine others will too. Is where a data value returns true, the "checked" attribute will be added to the element.  To be used with check boxes and radio buttons.

processElements("data-checked", template, data, settings, function ($elem, value) {
    if($elem.attr("type") == "checkbox" && (value == "true" || value == true)) {
        $elem.attr("checked", "checked");
    } else if($elem.attr("type") == "radio" && $elem.val() == value) {
        $elem.attr("checked", "checked");
    }
});

**Comment by codepb** [comment]
On reflection I am not keen on this. This would be the only thing that changes the value you bind, and there are data-formatters for that. I also do not want to add any data- attributes as there are enough already. This is all possible using the data-template-bind syntax, so I will close this issue.
