### ISSUE TITLE
Can't get children() of loaded template

### ISSUE THREAD

**Issue by dominiceales** [codepb/jquery-template#63]
Hi there,

I've started using this library and the templating part is working really well. 

The weird thing I have is that if I use a script tag with a src attribute the template has issues and the jQuery function .children() doesn't work.

Here is an example, see the console output and expand the object, there are no children. If you insert the template in the main HTML doc it works great.

Any ideas?

Cheers,
Dom

File: test.html
```html
<html>
	<head>
		<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js'></script>
		<script type='text/javascript' src='jquery.loadTemplate-1.4.4.js'></script>	</head>
	<body>
		<div id="output">

		</div>
		<script type="text/html" id="my_template" src="test.template.html"></script>
		<script type="text/javascript">
			jQuery(function ($) {
				$('#output').loadTemplate('#my_template',{div_id: "blah",message: 's\'up homes'});
				console.log($('#output').children());
			});
		</script>
	</body>
</html>
```

File: test.template.html
```html
<div data-id="div_id" data-content="message">
</div>
```

**Comment by codepb** [comment]
I imagine this is because loadTemplate by default is asynchronous. The console.log line is probably being called before the template is loaded. If you look at the settings, you can supply it as a callback instead and this should solve your problem

**Comment by dominiceales** [comment]
Thanks I'll give it go.
