### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by ssc-hrep3** [codepb/jquery-template#65]
Hi there,

I really like this jquery plugin, but unfortunately it is not available on bower (http://www.bower.io). Could you add it to bower for a simple dependency management?

Thanks!

**Comment by codepb** [comment]
Good idea, I will look to do this when I have time!

**Comment by ssc-hrep3** [comment]
I registered your repo at bower. It is now available under the name jquery-load-template and directly linked to this code repository. It was very simple:
```bower register jquery-load-template git://github.com/codepb/jquery-template.git```
