### ISSUE TITLE
Assign unique ID to each template post

### ISSUE THREAD

**Issue by greaveselliott** [codepb/jquery-template#66]
I'm using your plugin to loop through my template data to populate a Zurb Foundations Accordion http://foundation.zurb.com/docs/components/accordion.html

Each looped 'post' needs a unique ID, is there a simply way to get the current loop index?

Thanks in advance!

**Comment by codepb** [comment]
My suggestion would be to add a unique identifier to each item in your data. I don't think there is a way to get the current loop index, but you can have a look at the code and see if you can figure out a way!

**Comment by greaveselliott** [comment]
I ended up using a addTemplateFormat to add unique ID's to each 'post'. Its not very elegant but done the job ;D
