### ISSUE TITLE
How to set the value directly to a attribute, for example to ahref?

### ISSUE THREAD

**Issue by chriscodeweb** [codepb/jquery-template#68]
Hello, I am just playing with your template library for the first time.
I noticed a data-link and data-link-wrap options to set a href, but is there also a
way to directly acces the value? For example I would like to keep the existing properties on the a href.

`
 <a href="#" target="_blank" class="thumbnail" >
               <img data-src="logo" data-alt="name" class="img-responsive" />
 </a>
`

Something like this?
`
 <a href="${link}" target="_blank" class="thumbnail" >
               <img data-src="logo" data-alt="name" class="img-responsive" />
 </a>
`

Is it even possible to acces your data value without using the data- attribute?

Thanks in advance!

Regardss, Chris

**Comment by codepb** [comment]
Hi Chris,

If I understand correctly you would like to set the href value on the a tag without touching the other values. If that is the case you can use data-href on the a tag to set the value of the href to what you want on that and leave your other attributes alone. This should do what you want I believe.

Kind Regards

Paul

**Comment by chriscodeweb** [comment]
Hi Paul,
Thanks for your quick reply! Great work by the way! 
I will try data-href tomorrow at work. 

Have a nice evening.

Kind Regards,

Chris.

Date: Wed, 29 Apr 2015 10:44:15 -0700
