### ISSUE TITLE
Getting access to data on beforeInsert and afterInsert Callback

### ISSUE THREAD

**Issue by mafaust73** [codepb/jquery-template#69]
It would be a nice feature to have direct access to the data on certain callbacks. This gives us new possibilities to setup some elements based on the data (as required for example by some input wrapper libraries). Also, the need to first store the values in data attributes and then parse them again is removed. This makes initialization much more faster.

I modified only these two lines:
`settings.beforeInsert($templateHtml, data);`
`settings.afterInsert($templateHtml, data);`

Greetings

**Comment by codepb** [comment]
If you create a pull request I will add this into the code.

**Comment by fabbrikk** [comment]
@mafaust73 please create a pull request with this enhancement so this issue can be close.

**Comment by mafaust73** [comment]
I'll try to do it before my holiday. Sorry for the long delay.

Still love this library: simple, effektive and rock steady.
Martin
Am 07.08.2015 11:31 schrieb "Scandola Christian" <notifications@github.com>:
