### ISSUE TITLE
Problem success loadTemplate inside another template

### ISSUE THREAD

**Issue by alanMediacy** [codepb/jquery-template#72]
Hello, i have a page that is a template and inside have another template that is a list populate from ajax call. All works good.
Now i want to do a tour of pages using a plugin .
The problem is that if i call the tour function in the success of the second template  the list is not ready so the tour don't work. 
I think can be problem in the callback, it's like the second template take a success also when the first is success.

**Comment by codepb** [comment]
Could you provide an example of the issue for me to test with?

**Comment by codepb** [comment]
Closed due to not enough information
