### ISSUE TITLE
bower.json is not a proper json

### ISSUE THREAD

**Issue by leTel** [codepb/jquery-template#73]
There is an error when installing through bower :
bower jquery-load-template#*                          EMALFORMED Unexpected string
The issue come from the bower.json file. There is 3 issues in it. Here is the fixed json :

{
    "name": "jquery-load-template",
    "version": "1.5.0",
    "authors": [
        {
            "name": "Paul Burgess"
        }
    ],
    "homepage": "http://codepb.github.io/jquery-template/",
    "repository": {
        "type": "git",
        "url": "git://github.com/codepb/jquery-template.git"
    },
    "description": "jQuery plugin for loading and using templates. The plugin is designed to be simple yet powerful, and supports loading templates from within the page, or using AJAX to load html files.",
    "main": "jquery-loadTemplate/jquery.loadTemplate.js",
    "ignore": [
        "Examples",
        "tests",
        ".gitattributes",
        ".gitignore",
        ".travis.yml",
        "bower.json",
        "loadTemplate.jquery.json",
        "MIT-LICENSE.txt",
        "package.json",
        "readme.md"
    ],
    "keywords": [
        "templates",
        "templating",
        "jquery-plugin"
    ],
    "dependencies": {
        "jquery": ">=1.8"
    }
}

There is a missing ' , ' before "description", another one missing before "keywords" and an extra ' , ' after "dependencies".

**Comment by codepb** [comment]
Hi, can you create a pull request with the fix and I will close this issue.

**Comment by leTel** [comment]
Hi, I've made a pull request !

**Comment by codepb** [comment]
Fixed in #74
