### ISSUE TITLE
Array of string

### ISSUE THREAD

**Issue by MpStyle** [codepb/jquery-template#76]
Hi,

if I have a JSON like this: ["a","b","c","d","e"]
How can I have an output like the following?

&lt;ul>
    &lt;li>a&lt;/li>
    &lt;li>b&lt;/li>
    &lt;li>c&lt;/li>
    &lt;li>d&lt;/li>
    &lt;li>e&lt;/li>
&lt;/ul>

Thanks.

**Comment by codepb** [comment]
This is actually in the code for the Simple Example in the repository. Have a look at where it binds to "this". A simple jsfiddle is here: http://jsfiddle.net/upycc3sp/
