### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by rjcamatos** [codepb/jquery-template#79]
processElements("data-options-selected", template, data, settings, function ($elem, value) {
            $(value.options).each(function () {
                var $option = $("<option/>");
                if( value.selected == this ) $option.attr('selected','');
                $option.attr('value', this).text(this).appendTo($elem);
            });
        });

        processElements("data-checkbox", template, data, settings, function ($elem, value) {
            if( value ) $elem.attr('checked','');
        });

**Comment by codepb** [comment]
if you have something to add, can you make a pull request please.
