### ISSUE TITLE
loadTemplate , afterInsert problem

### ISSUE THREAD

**Issue by rjcamatos** [codepb/jquery-template#80]
loadTemplate with an array of JSON objects the the afterInsert callback cannot set data and events to the current element: Example:

function afterInsert(el,data) {               
                el.data('mydata',data);
 }

work arround:
$('#bla').loadTemplate('tpl.html', local_data[0], options);
$('#bla').loadTemplate('tpl.html', local_data[1], options);
$('#bla').loadTemplate('tpl.html', local_data[2], options);

**Comment by codepb** [comment]
I'm not sure what you are trying to do here?
