### ISSUE TITLE
loadTemplate , afterInsert problem

### ISSUE THREAD

**Issue by rjcamatos** [codepb/jquery-template#81]
loadTemplate with an array of JSON objects the afterInsert callback cannot set data and events to the current element: Example:

function afterInsert(el,data) {

el.click(function(){
console.log('THIS IS JUST CALLED FROM THE LAST TEMPLATE ELEMENT')
});
}

work arround:
$('#bla').loadTemplate('tpl.html', local_data[0], options);
$('#bla').loadTemplate('tpl.html', local_data[1], options);
$('#bla').loadTemplate('tpl.html', local_data[2], options);

**Comment by codepb** [comment]
I've just closed this issue as you didn't provide me with a clear example. Can you provide me with a jsfiddle example or a fully working code sample?
