### ISSUE TITLE
Unable to get external templates working.

### ISSUE THREAD

**Issue by chrisfromthelc** [codepb/jquery-template#82]
I'm having a bit of trouble trying to get external templates working.

I can take the same exact code, and enclose in `<script type="text/html" id="template">` tags per the instructions, and it works just fine. However, if I move that code out to an external template, I get nothing (not even the template's tags) in the main HTML container.

Relevent jQuery:
```
$.getJSON( devicesURL, function(result) {
  $.each(result, function( index, value ) {
    $(".main").loadTemplate("templates/test.html",result);
  });
});
```
Template:
```
    <div data-content="name"></div>
    <div data-content="restURL"></div>
```
Screenshot of the folder structure:
![screen shot 2016-01-03 at 11 09 47 am](https://cloud.githubusercontent.com/assets/8002138/12080025/965b2108-b20a-11e5-8139-06301284678d.png)

What am I missing?

**Comment by codepb** [comment]
Do you get any errors in the console when they don't load?

**Comment by codepb** [comment]
Closing as no response

**Comment by adaher15** [comment]
Hi
I am getting the same issue as "chrisfromthelc" the first time I tried to use this plugin, I tried to use the examples that comes with the project "SimpleExample", and I was getting the error "There was an error loading the template."
I tried to troubleshoot a bit to see where it's failing and found that the ajax call to load the template is the one that failed.
```
     $.ajax({
            url: templateUrl,
            async: settings.async,
            success: function (templateContent) {
                $templateContainer.html(templateContent);
                handleTemplateLoadingSuccess($templateContainer, template, selection, data, settings);
            },
            error: function (e) {
		console.debug("Error loading", e);
                handleTemplateLoadingError(template, selection, data, settings, e);
            }
```
There is no error in the console, but when I debuged the object "e" I couldn't see any useful information that would help me:
```
responseText: 	"<img data-src="authorPic...}]'>\n    </div>\n</div>\n"
status	        200
statusText        "OK"
```
Any idea what could be wrong?
Thank you
