### ISSUE TITLE
JSON Format Invalid

### ISSUE THREAD

**Issue by zhso** [codepb/jquery-template#84]
Release: https://github.com/codepb/jquery-template/archive/1.5.0.tar.gz
File: bower.json
in the "ignore" field, there has no comma and the end of array.

**Comment by codepb** [comment]
where is the issue sorry? It looks fine here: https://github.com/codepb/jquery-template/blob/master/bower.json

**Comment by zhso** [comment]
It's in the tar.gz files, i dont know why it in here, and build error? the `repository` part too, there no comma.

**Comment by codepb** [comment]
You are correct. Not sure why that would be the case. I'll investigate

**Comment by codepb** [comment]
How do I get to that file through the interface?

**Comment by codepb** [comment]
updated version, fixed in 1.5.1
