### ISSUE TITLE
Progressive number ?

### ISSUE THREAD

**Issue by fluctuate** [codepb/jquery-template#85]
Can i generate a progressive number into the template ?

**Comment by codepb** [comment]
I don't believe there is a way to do this in the templating engine as stands. However I would see this as being a concern of your data, therefore it should be generated and supplied with the data. Then you could just bind to it.

**Comment by fluctuate** [comment]
Imho, i still think that the plugin should still provide a progressive,
i might have need of it in order by to create my js App.
Yes, i can add it manually, but this is an other matter.

**Comment by codepb** [comment]
This is still possible, but it's not a presentation concern, it's a data concern. The following is the preferred solution from my perspective:

    var data = AjaxMethodReturnArray();
    for(var i =0; i <data.length;i++) {
        data[i].Id = i + 1;
    }
    $(".someElement").loadTemplate("template", data);

**Comment by fluctuate** [comment]
Thank you for your point of view.
