### ISSUE TITLE
How pre-select an item in DropDownBox ?

### ISSUE THREAD

**Issue by fluctuate** [codepb/jquery-template#91]
Now i'm working with "data-options", it works fine but, how can i set the "selected" item ?

**Comment by codepb** [comment]
this has been a bug for a while, and just fixed. You should be able to set the selected item by setting data-value on the select element to the value you want to be selected. This will only work in 1.5.7+

**Comment by fluctuate** [comment]
Tomorrow i'll try this feature, thank yu very much!
