### ISSUE TITLE
[Feature request] srcset for responsive images

### ISSUE THREAD

**Issue by soukupl** [codepb/jquery-template#93]
hi,
it would be great, if there is support for srcset to allow "retina" images.

My current implementation is not great, but working :)
I added processElements() for data-srcset (copy of data-src), so:

`processElements("data-srcset", template, data, settings, function ($elem, value) {
$elem.attr("srcset", applyFormatters($elem, value, "srcset", settings));
}, function ($elem) {
$elem.remove();
});`

template syntax is the same as src...
`<img data-src="mapimg" data-srcset="mapimg_srcset" data-alt="title">`

and the variable passed to jQuery is:
`
jQuery("#elm").loadTemplate(tpl_locationBox,
				{
					title: 'title is here',
					mapimg: 'image.jpg',
					mapimg_srcset: 'image.jpg 1x, image2x.jpg 2x'
				}
`

**Comment by codepb** [comment]
This is what data-template-bind is used for. I don't want to implement a specific attribute for binding to every possible attribute as that would get too overwhelming. Have a look at the bottom of the bindings section to see how to use it:

https://github.com/codepb/jquery-template#bindings

**Comment by soukupl** [comment]
I was thinking about extending the data-src to be ready to take string or array (if array is passed, src and srcset will be cretated).

`<img data-src="img" data-alt="title">`
or
`<img data-src='[{"1x": "img", "2x": "img_2x", "4x": "img_4x"}]' data-alt="title">`

but I wasn't able to hack this into your code (yet)

**Comment by codepb** [comment]
potentially. But it feels like that's adding some not intuitive behaviour into the mix. They are separate attributes to separate the concerns, and if I recall correctly, you should set both src and srcset on an image tag. Therefore, though this may be a nice feature for some, I don't see it as a lot of extra effort, and I don't think the implementation of this feature would be good for the plugin.

**Comment by soukupl** [comment]
ok, this is a good point :)
(and yes, the srcset is "extension" to src (now) and both attributes (src and srcset) needs to be set)
