### ISSUE TITLE
not worked in ie8

### ISSUE THREAD

**Issue by chengdh** [codepb/jquery-template#99]
in windows ie8,the jquery.parseHTML() return "",so the template update code cant work

**Comment by codepb** [comment]
The version of jQuery doesn't support IE 8 then? Or is it an issue in the way the plugin uses that method?

**Comment by chengdh** [comment]
I  use jquery 1.9,3 ,it support ie8

**Comment by codepb** [comment]
Can you provide an example that would fail in IE8?

**Comment by codepb** [comment]
I'm not going to fix this if it is only an issue in IE8. It seems this would be an issue with jquery.parseHTML
